### ISSUE TITLE
Need Option to switch ros versions for same OS (foxy/galactic, hubble/dasching, rolling)

### ISSUE THREAD

**Issue by planthaber** [dfki-ric/ros2-package_set#2]

**Comment by chhtz** [comment]
Is there an option to use variables in osdeps-files? Currently ros-2.osdeps-focal and ros-2.osdeps-jammy are almost identical, except for the version strings (which are likely redundant in this case) and the `ros-humble-` vs `ros-jammy-` prefixes. (There are a few other differences, but these get lost in the diff)

**Comment by chhtz** [comment]
What would also be convenient, if we could add a custom osdeps-style (similar to `gem:` or `pip:`) like:

    some_ros_package: ros2: some-ros-package

which then translates to `ros-${FLAVOR}-some-ros-package` (also allowing `FLAVOR=rolling`).

If that is not possible, I guess manually constructing everything with ruby is possible?

**Comment by planthaber** [comment]
The switch currently only allows it on a OS level:

It is organized by the setting an Autoproj.workspace.osdep_suffixes To load the matching file here:

https://github.com/dfki-ric/ros2-package_set/blob/master/init.rb#L9

I think that can easily be changed to ros release names with an question on initial aup with Autoproj.config.declare 


For custom ros deb packages, it should be possible to use the suffix files in other packages_sets down the line

**Comment by chhtz** [comment]
Yes, I guess it should be possible to also choose a file based on a different option. I was more asking if it is possible to avoid the redundancy between the `ros-2.osdeps-*` files (adding another almost identical file for Ubuntu24 at some point would add even more).

**Comment by planthaber** [comment]
Can you test
https://github.com/dfki-ric/ros2-package_set/pull/7

Now there are no checked in osdep files for rosdep and ros packages, on autoproj update, they are downloaded (if they don't exist)

**Comment by chhtz** [comment]
Looks good, I'll have a look later

**Comment by chhtz** [comment]
I guess this can be closed? (Fixed by PR #7)
